zalando/grafter

.travis.yml
build.sbt
depend.sbt

Closes #6 
(Apologies for opening the PR before the issue, I thought it was a simple change that didn't warrant a discussion.)

Cross-building to Scala (2.11.8, 2.12)

---

README.md

Fixed a code example in README.md

---

build.sbt

Please review @danielkarch @jcranky

#18 publish the submodules sources

---

README.md
core/src/main/scala/org/zalando/grafter/Queries.scala
core/src/main/scala/org/zalando/grafter/Reflect.scala
core/src/main/scala/org/zalando/grafter/Rewriter.scala
core/src/main/scala/org/zalando/grafter/syntax/package.scala
core/src/test/scala/org/zalando/grafter/QuerySpec.scala
depend.sbt

@danielkarch this can already be useful for our testing even if I have further methods in mind.

#27 added a collect method to collect distinct components of a given type

---

README.md

with better advice for compilation times
FYI @danielkarch

#29 rewrote the README integration section 

---

core/src/main/scala/org/zalando/grafter/Rewriter.scala
core/src/test/scala/org/zalando/grafter/RewriterSpec.scala

#35 do not throw exceptions when a component cannot be rewritten

---

README.md
build.sbt
core/src/main/scala/org/zalando/grafter/Rewriter.scala

Review @jcranky @taojang. This is a lot safer.

#37 restrict the classes which can be made singletons

---

README.md
build.sbt
core/src/main/scala/org/zalando/grafter/Rewriter.scala
core/src/test/scala/org/zalando/grafter/VisualizeSpec.scala

@taojang I messed up the merge for `1.4.6` and end-up not using breadth-first for `replaceFirst`.

#39 fix the merge issue with 1.4.6/7 which introduces a regression

---

README.md
build.sbt
core/src/main/scala/org/zalando/grafter/Rewriter.scala
core/src/test/scala/org/zalando/grafter/RewriterSpec.scala

This is not an ideal solution, I asked on the [Kiama mailing-list for advice](https://groups.google.com/d/msg/kiama/fiurVlFjnJk/o0DXCCFLBAAJ).

#44 added the possibility to replace value classes

---

.zappr.yaml

Set minimum approvals to two

---

build.sbt
core/src/main/scala/org/zalando/grafter/Visualize.scala
core/src/test/scala/org/zalando/grafter/VisualizeSpec.scala

@jcranky I'm running the test enough times to make sure this doesn't happen again.

#48 make sure .distinct works on the nodes of a graph

---

doc/installation.md

Update grafter documentation to the release 1.4.12 version

Update grafter version

---

.zappr.yaml

Fix internal compliance issues.

Change Zappr config to match with Zalando's compliance requirements

---

.travis.yml
build.sbt
core/src/main/scala/org/zalando/grafter/Queries.scala
core/src/main/scala/org/zalando/grafter/Visualize.scala
core/src/test/scala/org/zalando/grafter/RewriterSpec.scala
depend.sbt

#63 upgraded to kiama 2.1.0-RC1 and scala 2.12.2

---

.travis.yml
depend.sbt
project/plugins.sbt

Add code coverage

---

README.md

#74 Added a codecov badge

---

.travis.yml

Add code coverage and use codecov from the command line

---

.travis.yml

#77 aggregate coverage across sub-modules

---

macros/src/main/scala/org/zalando/grafter/macros/ReadersMacro.scala
macros/src/test/scala/org/zalando/grafter/macros/ReadersMacroTest.scala

#80 added an identity reader for the @readers annotation

---

.gitignore
core/src/main/scala/org/zalando/grafter/Queries.scala
core/src/main/scala/org/zalando/grafter/Visualize.scala

#81 use `pairs` and `fromOneStep` function from the latest kiama release

---

doc/installation.md

Amend version on installation page

---

build.sbt
depend.sbt

#86 upgraded Kiama to 2.1.0

---

doc/installation.md

#88 updated the version in the doc

---

build.sbt
depend.sbt
doc/installation.md
macros/src/main/scala/org/zalando/grafter/macros/DefaultReaderMacro.scala
macros/src/main/scala/org/zalando/grafter/macros/DefaultReaderOfMacro.scala
macros/src/main/scala/org/zalando/grafter/macros/ReaderMacro.scala
macros/src/main/scala/org/zalando/grafter/macros/ReaderMacros.scala
macros/src/main/scala/org/zalando/grafter/macros/ReaderOfMacro.scala
macros/src/main/scala/org/zalando/grafter/macros/ReadersMacro.scala
macros/src/test/scala/org/zalando/grafter/macros/DefaultReaderMacroSpec.scala
macros/src/test/scala/org/zalando/grafter/macros/DefaultReaderOfMacroSpec.scala
macros/src/test/scala/org/zalando/grafter/macros/DefaultReaderOfMacroTest.scala
macros/src/test/scala/org/zalando/grafter/macros/ReaderMacroTest.scala
macros/src/test/scala/org/zalando/grafter/macros/ReaderOfMacroSpec.scala
macros/src/test/scala/org/zalando/grafter/macros/ReadersMacroSpec.scala
macros/src/test/scala/org/zalando/grafter/macros/ReadersMacroTest.scala

#90 rewrote the macro annotations using scalameta

---

build.sbt
core/src/main/scala/org/zalando/grafter/Visualize.scala
doc/inspect-app-graph.md
tests/src/test/scala/org/zalando/grafter/VisualizeSpec.scala

Review @jcranky 
I had a go at tinbox and the results look good.

Show attributes in dot graphs. fixes #94

---

build.sbt
core/src/main/scala/org/zalando/grafter/Queries.scala
core/src/main/scala/org/zalando/grafter/Visualize.scala
doc/inspect-app-graph.md
tests/src/test/scala/org/zalando/grafter/VisualizeSpec.scala

@jcranky this is necessary to get a nice display of graphs with a minimum of specification.

#105 filter keeps parents, exclude removes children

---

CONTRIBUTING.md
README.md

Contributors need to be made aware of the terms and conditions under which they contribute to this repository.

Add inbound license notice

---

core/src/main/scala/org/zalando/grafter/Rewriter.scala
tests/src/test/scala/org/zalando/grafter/RewriterSpec.scala

Closes #108
`oldThing.replaceOrFail(s)` returns Some(newThing) if replacing with `s` was successful,
or `None` otherwise.
@etorreborre @jcranky Is that the sort of thing you had in mind?

Add method `replacedWith`

---

build.sbt

in order to publish a new version.

set version to 2.2.2

---

build.sbt
core/src/main/scala/org/zalando/grafter/Rewriter.scala
doc/fullapp.md
doc/start-stop.md
examples/src/test/scala/org/zalando/grafter/examples/simple/Application.scala
tests/src/test/scala/org/zalando/grafter/RewriterSpec.scala

Review @danielkarch 
closes #111

#111 renamed Rewriter.start/stop to startAll/stopAll

---

build.sbt
depend.sbt
version.sbt

Update to use cats 1

---

.travis.yml
build.sbt
project/build.properties
project/plugins.sbt

#120 use sbt 1.x

---

.travis.yml
build.sbt
depend.sbt
macros/src/main/scala/org/zalando/grafter/macros/ReadersMacro.scala
macros/src/test/scala/org/zalando/grafter/macros/ReadersFMacroTest.scala

This PR adds the ability to have higher order types as the target of `@readers` macro.
I'm basically stumbling around in the dark here, so would love someone to take a look at it. 
As far as I can tell it does what I need it to do for my use case, but I'm not sure if it makes other things harder to do.
This fixes #118 
I also upgraded some dependencies, let me know if you want me to put that in a separate PR.

Improve readers macro
